import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { accountSwapDestinationRows, SWAP_EVENTS_SQL, QUEUE_AMOUNT_IN_SQL, QUEUE_AMOUNT_OUT_SQL, type AccountSwapQueueRow } from '../src/db/accountSwapQueue.ts'

const queued: AccountSwapQueueRow = {
  queued_at: '2026-07-16 12:00:00.000',
  block_height: 42,
  event_index: 7,
  extrinsic_index: 3,
  block_timestamp: '2026-07-16 11:59:59',
  event_name: 'Router.Executed',
  asset_in: 0,
  asset_out: 5,
  amount_in: '1000000000000',
  amount_out: '2000000',
  ingested_at: '2026-07-16 12:00:00',
}

describe('account swap queue', () => {
  it('resolves a queued event from only its exact extrinsic tuple', () => {
    const rows = accountSwapDestinationRows([queued], [
      { block_height: 41, extrinsic_index: 3, signer: 'wrong', effective_signer: null },
      { block_height: 42, extrinsic_index: 3, signer: 'alice', effective_signer: null },
    ])

    expect(rows).toHaveLength(1)
    expect(rows[0]).toMatchObject({ account: 'alice', signer: 'alice', block_height: 42, event_index: 7 })
  })

  it('deduplicates identical signer forms and retains an effective signer', () => {
    const duplicate = accountSwapDestinationRows([queued], [
      { block_height: 42, extrinsic_index: 3, signer: 'alice', effective_signer: 'alice' },
    ])
    const effective = accountSwapDestinationRows([queued], [
      { block_height: 42, extrinsic_index: 3, signer: null, effective_signer: 'evm-alice' },
    ])

    expect(duplicate.map(row => row.account)).toEqual(['alice'])
    expect(effective.map(row => [row.account, row.signer])).toEqual([['evm-alice', 'evm-alice']])
  })

  // A swap dispatched from a block hook has no extrinsic, so no signer: its actor
  // comes from the Broadcast event via swap_actor. Before this, such a row was
  // dropped for want of an extrinsic and the swap never reached its owner's page —
  // a $90k Treasury swap among them.
  it('attributes a hook swap to its Broadcast swapper instead of a signer', () => {
    const hook: AccountSwapQueueRow = { ...queued, extrinsic_index: null }
    const rows = accountSwapDestinationRows([hook], [], new Map([['42:7', 'treasury']]))

    expect(rows).toHaveLength(1)
    expect(rows[0]).toMatchObject({ account: 'treasury', extrinsic_index: null, block_height: 42, event_index: 7 })
    // No signer signed it; claiming one would name an actor that does not exist.
    expect(rows[0].signer).toBe('')
  })

  // Unresolved covers three cases that must all stay out rather than be attributed
  // to the router pallet: pre-Broadcast history, a placeholder swapper, and a DCA
  // execution (already rendered by the DCA path, so a second row would double it).
  it('drops a hook swap with no resolved swapper', () => {
    const hook: AccountSwapQueueRow = { ...queued, extrinsic_index: null }
    expect(accountSwapDestinationRows([hook], [], new Map())).toEqual([])
    // Keyed by the swap's own event, not merely its block.
    expect(accountSwapDestinationRows([hook], [], new Map([['42:9', 'someone-else']]))).toEqual([])
  })
})

// The seed's catch-up INSERT is a hand-copy of account_swap_activity_queue_mv, run
// once at the hand-off from the former synchronous view. A copy admits drift for
// free: a family the live view ingests but the seed omits leaves a silent hole in
// exactly the rows the hand-off exists to cover, and a family only the seed names
// (three Hydration pallets outlived the fork here) writes rows nothing else can
// produce. Nothing pinned the two together, so they are pinned here.
describe('account swap queue seed parity', () => {
  const schema = readFileSync(new URL('../../clickhouse/schema/003_materialized_views.sql', import.meta.url), 'utf8')
  const view = schema.split(/^CREATE MATERIALIZED VIEW /m)
    .find(s => s.startsWith('IF NOT EXISTS price_data.account_swap_activity_queue_mv ')) ?? ''

  const eventNames = (sql: string) => [...new Set([...sql.matchAll(/'([A-Za-z]+\.[A-Za-z]+Executed)'/g)].map(m => m[1]))].sort()

  it('names the same swap families the materialized view ingests', () => {
    expect(view, 'account_swap_activity_queue_mv missing from 003_materialized_views.sql').toBeTruthy()
    // The view's WHERE list is its only Executed-name set; the seed's is the constant.
    expect(eventNames(SWAP_EVENTS_SQL)).toEqual(eventNames(view.slice(view.indexOf('WHERE'))))
  })

  it("extracts the two amounts with the view's own expressions", () => {
    // Compared modulo formatting only: the schema file is regenerated by SHOW
    // CREATE and spaces its lists, the hand-written constant does not.
    const normalize = (sql: string) => sql.replace(/\s+/g, ' ').replace(/, +'/g, `,'`)
    for (const [expression, alias] of [[QUEUE_AMOUNT_IN_SQL, 'amount_in'], [QUEUE_AMOUNT_OUT_SQL, 'amount_out']] as const) {
      const at = view.indexOf(` AS ${alias}`)
      let depth = 0
      let start = -1
      for (let i = at - 1; i >= 0 && start < 0; i--) {
        if (view[i] === ')') depth++
        else if (view[i] === '(' && --depth === 0) start = i
      }
      expect(normalize(expression), alias).toBe(normalize(`multiIf${view.slice(start, at)}`))
    }
  })
})
