-- Materialized views (source + TO-target tables exist from 001).
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.account_activity_v3_mv TO price_data.account_activity_v3 (`account` String, `block_height` UInt32, `event_index` UInt32, `extrinsic_index` Nullable(UInt32), `event_name` LowCardinality(String), `block_timestamp` DateTime, `is_module_transfer` UInt8, `asset_id` UInt32, `amount` UInt256, `has_amount` UInt8) AS WITH multiIf(event_name IN ('XYK.SellExecuted', 'LBP.SellExecuted'), JSONExtractString(args_json, 'salePrice'), event_name IN ('XYK.BuyExecuted', 'LBP.BuyExecuted'), JSONExtractString(args_json, 'amount'), (event_name IN ('Router.Executed')), JSONExtractString(args_json, 'amountOut'), JSONHas(args_json, 'claimed'), JSONExtractString(args_json, 'claimed'), JSONHas(args_json, 'amount'), JSONExtractString(args_json, 'amount'), JSONHas(args_json, 'balance'), JSONExtractString(args_json, 'balance'), JSONHas(args_json, 'vote'), multiIf(JSONExtractString(JSONExtractRaw(args_json, 'vote'), '__kind') = 'Split', toString(toUInt256OrZero(JSONExtractString(JSONExtractRaw(args_json, 'vote'), 'aye')) + toUInt256OrZero(JSONExtractString(JSONExtractRaw(args_json, 'vote'), 'nay'))), JSONExtractString(JSONExtractRaw(args_json, 'vote'), '__kind') = 'SplitAbstain', toString((toUInt256OrZero(JSONExtractString(JSONExtractRaw(args_json, 'vote'), 'aye')) + toUInt256OrZero(JSONExtractString(JSONExtractRaw(args_json, 'vote'), 'nay'))) + toUInt256OrZero(JSONExtractString(JSONExtractRaw(args_json, 'vote'), 'abstain'))), JSONExtractString(JSONExtractRaw(args_json, 'vote'), 'balance')), '') AS raw_amount SELECT arrayJoin(arrayDistinct(extractAll(args_json, '"(0x[0-9a-f]{64})"'))) AS account, block_height, event_index, extrinsic_index, event_name, block_timestamp, toUInt8((event_name IN ('Balances.Transfer', 'Tokens.Transfer', 'Currencies.Transferred')) AND ((JSONExtractString(args_json, 'from') LIKE '0x6d6f646c%') OR (JSONExtractString(args_json, 'to') LIKE '0x6d6f646c%'))) AS is_module_transfer, toUInt32(greatest(0, multiIf((event_name IN ('Router.Executed', 'XYK.SellExecuted', 'XYK.BuyExecuted', 'LBP.SellExecuted', 'LBP.BuyExecuted')), JSONExtractInt(args_json, 'assetOut'), event_name = 'Balances.Transfer', 0, JSONHas(args_json, 'rewardCurrency'), JSONExtractInt(args_json, 'rewardCurrency'), JSONHas(args_json, 'currencyId'), JSONExtractInt(args_json, 'currencyId'), JSONHas(args_json, 'currency_id'), JSONExtractInt(args_json, 'currency_id'), JSONHas(args_json, 'assetId'), JSONExtractInt(args_json, 'assetId'), JSONHas(args_json, 'asset_id'), JSONExtractInt(args_json, 'asset_id'), JSONHas(args_json, 'poolId'), JSONExtractInt(args_json, 'poolId'), JSONHas(args_json, 'assetA'), JSONExtractInt(args_json, 'assetA'), 0))) AS asset_id, toUInt256OrZero(raw_amount) AS amount, toUInt8(raw_amount != '') AS has_amount FROM price_data.raw_events;
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.account_asset_latest_balances_mv TO price_data.account_asset_latest_balances (`account_id` String, `asset_id` String, `total_state` AggregateFunction(argMax, Nullable(String), UInt32), `free_state` AggregateFunction(argMax, Nullable(String), UInt32), `reserved_state` AggregateFunction(argMax, Nullable(String), UInt32), `last_block_state` AggregateFunction(max, UInt32)) AS SELECT account_id, asset_id, argMaxState(total, block_height) AS total_state, argMaxState(free, block_height) AS free_state, argMaxState(reserved, block_height) AS reserved_state, maxState(block_height) AS last_block_state FROM price_data.raw_balance_observations WHERE (account_id != '') AND (asset_id != '') GROUP BY account_id, asset_id;
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.account_balance_history_mv TO price_data.account_balance_history (`account_id` String, `asset_id` String, `asset_kind` LowCardinality(String), `block_height` UInt32, `block_timestamp` DateTime, `observation_id` String, `total` String, `ingested_at` DateTime) AS SELECT account_id, asset_id, asset_kind, block_height, block_timestamp, observation_id, ifNull(total, '') AS total, ingested_at FROM price_data.raw_balance_observations WHERE (account_id != '') AND (asset_id != '');
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.account_balance_hourly_mv TO price_data.account_balance_hourly (`account_id` String, `asset_id` String, `interval_start` DateTime, `balance_state` AggregateFunction(argMax, String, Tuple(UInt32, String, DateTime)), `block_state` AggregateFunction(argMax, UInt32, Tuple(UInt32, String, DateTime)), `first_block_state` AggregateFunction(min, UInt32), `last_block_state` AggregateFunction(max, UInt32), `first_timestamp_state` AggregateFunction(min, DateTime), `last_timestamp_state` AggregateFunction(max, DateTime)) AS WITH tuple(block_height, observation_id, ingested_at) AS version SELECT account_id, asset_id, toStartOfHour(block_timestamp) AS interval_start, argMaxState(ifNull(toString(toUInt256OrZero(total)), '0'), version) AS balance_state, argMaxState(block_height, version) AS block_state, minState(block_height) AS first_block_state, maxState(block_height) AS last_block_state, minState(block_timestamp) AS first_timestamp_state, maxState(block_timestamp) AS last_timestamp_state FROM price_data.raw_balance_observations WHERE (account_id != '') AND (asset_id != '') GROUP BY account_id, asset_id, interval_start;
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.account_balance_weekly_mv TO price_data.account_balance_weekly (`account_id` String, `asset_id` String, `week_start` Date, `balance_state` AggregateFunction(argMax, String, Tuple(UInt32, UInt32, String, DateTime)), `activity_state` AggregateFunction(uniq, Tuple(UInt32, Nullable(UInt32))), `last_block_state` AggregateFunction(max, UInt32)) AS SELECT account_id, asset_id, toMonday(block_timestamp) AS week_start, argMaxState(coalesce(total, '0'), tuple(block_height, ifNull(source_event_index, toUInt32(4294967295)), observation_id, ingested_at)) AS balance_state, uniqState(tuple(block_height, source_event_index)) AS activity_state, maxState(block_height) AS last_block_state FROM price_data.raw_balance_observations WHERE (account_id != '') AND (asset_id != '') GROUP BY account_id, asset_id, week_start;
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.account_swap_activity_queue_mv TO price_data.account_swap_activity_queue (`queued_at` DateTime64(3), `block_height` UInt32, `event_index` UInt32, `extrinsic_index` Nullable(UInt32), `block_timestamp` DateTime, `event_name` LowCardinality(String), `asset_in` UInt32, `asset_out` UInt32, `amount_in` String, `amount_out` String, `ingested_at` DateTime) AS SELECT now64(3) AS queued_at, block_height, event_index, extrinsic_index, block_timestamp, event_name, toUInt32(greatest(0, JSONExtractInt(args_json, 'assetIn'))) AS asset_in, toUInt32(greatest(0, JSONExtractInt(args_json, 'assetOut'))) AS asset_out, multiIf(event_name IN ('XYK.SellExecuted', 'LBP.SellExecuted'), JSONExtractString(args_json, 'amount'), event_name IN ('XYK.BuyExecuted', 'LBP.BuyExecuted'), JSONExtractString(args_json, 'buyPrice'), JSONExtractString(args_json, 'amountIn')) AS amount_in, multiIf(event_name IN ('XYK.SellExecuted', 'LBP.SellExecuted'), JSONExtractString(args_json, 'salePrice'), event_name IN ('XYK.BuyExecuted', 'LBP.BuyExecuted'), JSONExtractString(args_json, 'amount'), JSONExtractString(args_json, 'amountOut')) AS amount_out, ingested_at FROM price_data.raw_events WHERE (event_name IN ('Router.Executed', 'Router.RouteExecuted', 'XYK.SellExecuted', 'XYK.BuyExecuted', 'LBP.SellExecuted', 'LBP.BuyExecuted')) AND ((extrinsic_index IS NOT NULL) OR (event_name IN ('Router.Executed', 'Router.RouteExecuted')));
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.account_transfer_activity_mv TO price_data.account_transfer_activity (`account` String, `block_height` UInt32, `event_index` UInt32, `extrinsic_index` Nullable(UInt32), `block_timestamp` DateTime, `event_name` LowCardinality(String), `call_address` Nullable(String), `from_account` String, `to_account` String, `amount` String, `asset_id` UInt32) AS WITH if(JSONHas(args_json, 'from'), JSONExtractString(args_json, 'from'), JSONExtractString(args_json, 1)) AS from_account, if(JSONHas(args_json, 'to'), JSONExtractString(args_json, 'to'), JSONExtractString(args_json, 2)) AS to_account SELECT arrayJoin(arrayFilter(account -> (account != ''), arrayDistinct([from_account, to_account]))) AS account, block_height, event_index, extrinsic_index, block_timestamp, event_name, call_address, from_account, to_account, if(JSONHas(args_json, 'amount'), JSONExtractString(args_json, 'amount'), JSONExtractString(args_json, 3)) AS amount, toUInt32(if(event_name = 'Balances.Transfer', 0, multiIf(JSONHas(args_json, 'currencyId'), JSONExtractInt(args_json, 'currencyId'), JSONHas(args_json, 'currency_id'), JSONExtractInt(args_json, 'currency_id'), JSONHas(args_json, 'assetId'), JSONExtractInt(args_json, 'assetId'), JSONHas(args_json, 'asset_id'), JSONExtractInt(args_json, 'asset_id'), 0))) AS asset_id FROM price_data.raw_events WHERE event_name IN ('Balances.Transfer', 'Tokens.Transfer', 'Currencies.Transferred');
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.account_transfer_activity_treasury_mv TO price_data.account_transfer_activity (`account` String, `block_height` UInt32, `event_index` UInt32, `extrinsic_index` Nullable(UInt32), `block_timestamp` DateTime, `event_name` LowCardinality(String), `call_address` Nullable(String), `from_account` String, `to_account` String, `amount` String, `asset_id` UInt32) AS WITH '0x6d6f646c70792f74727372790000000000000000000000000000000000000000' AS from_account, JSONExtractString(args_json, 'account') AS to_account SELECT arrayJoin(arrayFilter(account -> (account != ''), arrayDistinct([from_account, to_account]))) AS account, block_height, event_index, extrinsic_index, block_timestamp, event_name, call_address, from_account, to_account, JSONExtractString(args_json, 'award') AS amount, toUInt32(0) AS asset_id FROM price_data.raw_events WHERE event_name = 'Treasury.Awarded';
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.activity_histogram_events_mv TO price_data.activity_histogram_events (`day` Date, `block_height` UInt32, `event_index` UInt32, `activity_index` UInt32, `event_name` LowCardinality(String), `asset_refs` Array(UInt32), `ingested_at` DateTime) AS SELECT toDate(block_timestamp) AS day, block_height, event_index, toUInt32(if((event_name IN ('Router.Executed', 'XYK.SellExecuted', 'XYK.BuyExecuted', 'LBP.SellExecuted', 'LBP.BuyExecuted')), ifNull(extrinsic_index, event_index), event_index)) AS activity_index, event_name, multiIf((event_name IN ('Balances.Transfer', 'Tokens.Transfer', 'Currencies.Transferred')), [toUInt32(if(event_name = 'Balances.Transfer', 0, multiIf(JSONHas(args_json, 'currencyId'), greatest(0, JSONExtractInt(args_json, 'currencyId')), JSONHas(args_json, 'currency_id'), greatest(0, JSONExtractInt(args_json, 'currency_id')), JSONHas(args_json, 'assetId'), greatest(0, JSONExtractInt(args_json, 'assetId')), JSONHas(args_json, 'asset_id'), greatest(0, JSONExtractInt(args_json, 'asset_id')), 0)))], (event_name IN ('Router.Executed', 'XYK.SellExecuted', 'XYK.BuyExecuted', 'LBP.SellExecuted', 'LBP.BuyExecuted')), arrayDistinct([toUInt32(greatest(0, JSONExtractInt(args_json, 'assetIn'))), toUInt32(greatest(0, JSONExtractInt(args_json, 'assetOut')))]), (event_name IN ('XYK.LiquidityAdded', 'XYK.LiquidityRemoved', 'XYK.PoolCreated', 'XYK.PoolDestroyed', 'XYKLiquidityMining.RewardClaimed')), arrayDistinct(arrayConcat(if(JSONHas(args_json, 'rewardCurrency'), [toUInt32(greatest(0, JSONExtractInt(args_json, 'rewardCurrency')))], CAST([], 'Array(UInt32)')), if(JSONHas(args_json, 'assetId'), [toUInt32(greatest(0, JSONExtractInt(args_json, 'assetId')))], CAST([], 'Array(UInt32)')), if(JSONHas(args_json, 'asset_id'), [toUInt32(greatest(0, JSONExtractInt(args_json, 'asset_id')))], CAST([], 'Array(UInt32)')), if(JSONHas(args_json, 'poolId'), [toUInt32(greatest(0, JSONExtractInt(args_json, 'poolId')))], CAST([], 'Array(UInt32)')), if(JSONHas(args_json, 'assetA'), [toUInt32(greatest(0, JSONExtractInt(args_json, 'assetA')))], CAST([], 'Array(UInt32)')), if(JSONHas(args_json, 'assetB'), [toUInt32(greatest(0, JSONExtractInt(args_json, 'assetB')))], CAST([], 'Array(UInt32)')), arrayMap(item -> toUInt32(greatest(0, JSONExtractInt(item, 'assetId'))), JSONExtractArrayRaw(args_json, 'assets')))), (event_name IN ('ConvictionVoting.Voted', 'Democracy.Voted', 'Council.Voted', 'TechnicalCommittee.Voted')), [toUInt32(0)], CAST([], 'Array(UInt32)')) AS asset_refs, ingested_at FROM price_data.raw_events WHERE event_name IN ('Router.Executed', 'XYK.SellExecuted', 'XYK.BuyExecuted', 'LBP.SellExecuted', 'LBP.BuyExecuted', 'XYK.LiquidityAdded', 'XYK.LiquidityRemoved', 'XYK.PoolCreated', 'XYK.PoolDestroyed', 'XYKLiquidityMining.RewardClaimed', 'Balances.Transfer', 'Tokens.Transfer', 'Currencies.Transferred', 'ConvictionVoting.Voted', 'Democracy.Voted', 'Council.Voted', 'TechnicalCommittee.Voted');
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.asset_swap_activity_mv TO price_data.asset_swap_activity (`asset_id` UInt32, `block_height` UInt32, `event_index` UInt32, `extrinsic_index` Nullable(UInt32), `block_timestamp` DateTime, `event_name` LowCardinality(String), `who` String, `asset_in` UInt32, `asset_out` UInt32, `amount_in` String, `amount_out` String) AS SELECT arrayJoin(arrayDistinct([toUInt32(greatest(0, JSONExtractInt(args_json, 'assetIn'))), toUInt32(greatest(0, JSONExtractInt(args_json, 'assetOut')))])) AS asset_id, block_height, event_index, extrinsic_index, block_timestamp, event_name, JSONExtractString(args_json, 'who') AS who, toUInt32(greatest(0, JSONExtractInt(args_json, 'assetIn'))) AS asset_in, toUInt32(greatest(0, JSONExtractInt(args_json, 'assetOut'))) AS asset_out, multiIf(event_name IN ('XYK.SellExecuted', 'LBP.SellExecuted'), JSONExtractString(args_json, 'amount'), event_name IN ('XYK.BuyExecuted', 'LBP.BuyExecuted'), JSONExtractString(args_json, 'buyPrice'), JSONExtractString(args_json, 'amountIn')) AS amount_in, multiIf(event_name IN ('XYK.SellExecuted', 'LBP.SellExecuted'), JSONExtractString(args_json, 'salePrice'), event_name IN ('XYK.BuyExecuted', 'LBP.BuyExecuted'), JSONExtractString(args_json, 'amount'), JSONExtractString(args_json, 'amountOut')) AS amount_out FROM price_data.raw_events WHERE event_name IN ('Router.Executed', 'Router.RouteExecuted', 'XYK.SellExecuted', 'XYK.BuyExecuted', 'LBP.SellExecuted', 'LBP.BuyExecuted');
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.daily_event_identity_counts_v2_mv TO price_data.daily_chain_identity_counts_v2 (`kind` String, `day` Date, `identity_state` AggregateFunction(groupBitmap, UInt64)) AS SELECT 'events' AS kind, toDate(block_timestamp) AS day, groupBitmapState(bitOr(bitShiftLeft(toUInt64(event_index), 32), toUInt64(block_height))) AS identity_state FROM price_data.raw_events GROUP BY day;
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.daily_extrinsic_identity_counts_v2_mv TO price_data.daily_chain_identity_counts_v2 (`kind` String, `day` Date, `identity_state` AggregateFunction(groupBitmap, UInt64)) AS SELECT 'extrinsics' AS kind, toDate(block_timestamp) AS day, groupBitmapState(bitOr(bitShiftLeft(toUInt64(extrinsic_index), 32), toUInt64(block_height))) AS identity_state FROM price_data.raw_extrinsics WHERE coalesce(signer, effective_signer) IS NOT NULL GROUP BY day;
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.event_asset_refs_mv TO price_data.event_asset_refs (`asset_id` UInt32, `event_name` LowCardinality(String), `block_height` UInt32, `event_index` UInt32, `extrinsic_index` Nullable(UInt32), `block_timestamp` DateTime, `ingested_at` DateTime) AS SELECT arrayJoin(arrayDistinct(arrayConcat(if(event_name = 'Balances.Transfer', [toUInt32(0)], emptyArrayUInt32()), if(JSONHas(args_json, 'currencyId'), [toUInt32(greatest(0, JSONExtractInt(args_json, 'currencyId')))], emptyArrayUInt32()), if(JSONHas(args_json, 'currency_id'), [toUInt32(greatest(0, JSONExtractInt(args_json, 'currency_id')))], emptyArrayUInt32()), if(JSONHas(args_json, 'assetId'), [toUInt32(greatest(0, JSONExtractInt(args_json, 'assetId')))], emptyArrayUInt32()), if(JSONHas(args_json, 'asset_id'), [toUInt32(greatest(0, JSONExtractInt(args_json, 'asset_id')))], emptyArrayUInt32()), if(JSONHas(args_json, 'assetIn'), [toUInt32(greatest(0, JSONExtractInt(args_json, 'assetIn')))], emptyArrayUInt32()), if(JSONHas(args_json, 'assetOut'), [toUInt32(greatest(0, JSONExtractInt(args_json, 'assetOut')))], emptyArrayUInt32()), if(JSONHas(args_json, 'assetA'), [toUInt32(greatest(0, JSONExtractInt(args_json, 'assetA')))], emptyArrayUInt32()), if(JSONHas(args_json, 'assetB'), [toUInt32(greatest(0, JSONExtractInt(args_json, 'assetB')))], emptyArrayUInt32()), if(JSONHas(args_json, 'poolId'), [toUInt32(greatest(0, JSONExtractInt(args_json, 'poolId')))], emptyArrayUInt32()), if(JSONHas(args_json, 'rewardCurrency'), [toUInt32(greatest(0, JSONExtractInt(args_json, 'rewardCurrency')))], emptyArrayUInt32()), if(JSONHas(args_json, 'currency'), [toUInt32(greatest(0, JSONExtractInt(args_json, 'currency')))], emptyArrayUInt32()), arrayMap(item -> toUInt32(greatest(0, JSONExtractInt(item, 'assetId'))), JSONExtractArrayRaw(args_json, 'assets'))))) AS asset_id, event_name, block_height, event_index, extrinsic_index, block_timestamp, ingested_at FROM price_data.raw_events;
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.governance_vote_calls_mv TO price_data.governance_vote_calls (`pallet` LowCardinality(String), `ref_index` UInt32, `block_height` UInt32, `extrinsic_index` Nullable(UInt32), `call_address` String, `block_timestamp` DateTime, `call_name` LowCardinality(String), `who` String, `vote_kind` LowCardinality(String), `vote_byte` UInt16, `balance` String, `aye` String, `nay` String, `abstain` String, `success` UInt8, `ingested_at` DateTime) AS SELECT if(call_name LIKE 'Democracy.%', 'democracy', 'opengov') AS pallet, toUInt32(greatest(0, multiIf(call_name = 'ConvictionVoting.vote', JSONExtractInt(args_json, 'pollIndex'), call_name = 'Democracy.vote', JSONExtractInt(args_json, 'refIndex'), JSONExtractInt(args_json, 'index')))) AS ref_index, block_height, extrinsic_index, call_address, block_timestamp, call_name, lower(if(call_name IN ('ConvictionVoting.remove_other_vote', 'ConvictionVoting.force_remove_vote', 'Democracy.remove_other_vote', 'Democracy.force_remove_vote'), JSONExtractString(args_json, 'target'), JSONExtractString(ifNull(origin_json, ''), 'value', 'value'))) AS who, JSONExtractString(args_json, 'vote', '__kind') AS vote_kind, toUInt16(greatest(0, JSONExtractInt(args_json, 'vote', 'vote'))) AS vote_byte, JSONExtractString(args_json, 'vote', 'balance') AS balance, JSONExtractString(args_json, 'vote', 'aye') AS aye, JSONExtractString(args_json, 'vote', 'nay') AS nay, JSONExtractString(args_json, 'vote', 'abstain') AS abstain, toUInt8(ifNull(success, 0)) AS success, ingested_at FROM price_data.raw_calls WHERE call_name IN ('ConvictionVoting.vote', 'ConvictionVoting.remove_vote', 'ConvictionVoting.remove_other_vote', 'ConvictionVoting.force_remove_vote', 'Democracy.vote', 'Democracy.remove_vote', 'Democracy.remove_other_vote', 'Democracy.force_remove_vote');
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.liquidity_activity_mv TO price_data.liquidity_activity (`block_height` UInt32, `event_index` UInt32, `extrinsic_index` Nullable(UInt32), `block_timestamp` DateTime, `event_name` LowCardinality(String), `who` String, `asset_id` UInt32, `amount` String, `amount_a` String, `asset_b` UInt32, `pool_account` String, `asset_refs` Array(UInt32), `ingested_at` DateTime) AS SELECT block_height, event_index, extrinsic_index, block_timestamp, event_name, if(JSONHas(args_json, 'who'), JSONExtractString(args_json, 'who'), JSONExtractString(args_json, 'owner')) AS who, toUInt32(greatest(0, multiIf(JSONHas(args_json, 'rewardCurrency'), JSONExtractInt(args_json, 'rewardCurrency'), JSONHas(args_json, 'assetId'), JSONExtractInt(args_json, 'assetId'), JSONHas(args_json, 'poolId'), JSONExtractInt(args_json, 'poolId'), JSONHas(args_json, 'assetA'), JSONExtractInt(args_json, 'assetA'), JSONHas(args_json, 'asset'), JSONExtractInt(args_json, 'asset'), JSONExtractInt(args_json, 'asset_id')))) AS asset_id, multiIf(JSONHas(args_json, 'claimed'), JSONExtractString(args_json, 'claimed'), JSONHas(args_json, 'amount'), JSONExtractString(args_json, 'amount'), '') AS amount, JSONExtractString(args_json, 'amountA') AS amount_a, toUInt32(greatest(0, JSONExtractInt(args_json, 'assetB'))) AS asset_b, JSONExtractString(args_json, 'pool') AS pool_account, arrayDistinct(arrayConcat(if(JSONHas(args_json, 'rewardCurrency'), [toUInt32(greatest(0, JSONExtractInt(args_json, 'rewardCurrency')))], CAST([], 'Array(UInt32)')), if(JSONHas(args_json, 'assetId'), [toUInt32(greatest(0, JSONExtractInt(args_json, 'assetId')))], CAST([], 'Array(UInt32)')), if(JSONHas(args_json, 'asset_id'), [toUInt32(greatest(0, JSONExtractInt(args_json, 'asset_id')))], CAST([], 'Array(UInt32)')), if(JSONHas(args_json, 'asset'), [toUInt32(greatest(0, JSONExtractInt(args_json, 'asset')))], CAST([], 'Array(UInt32)')), if(JSONHas(args_json, 'poolId'), [toUInt32(greatest(0, JSONExtractInt(args_json, 'poolId')))], CAST([], 'Array(UInt32)')), if(JSONHas(args_json, 'assetA'), [toUInt32(greatest(0, JSONExtractInt(args_json, 'assetA')))], CAST([], 'Array(UInt32)')), if(JSONHas(args_json, 'assetB'), [toUInt32(greatest(0, JSONExtractInt(args_json, 'assetB')))], CAST([], 'Array(UInt32)')), arrayMap(item -> toUInt32(greatest(0, JSONExtractInt(item, 'assetId'))), JSONExtractArrayRaw(args_json, 'assets')))) AS asset_refs, ingested_at FROM price_data.raw_events WHERE event_name IN ('XYK.LiquidityAdded', 'XYK.LiquidityRemoved', 'XYK.PoolCreated', 'XYK.PoolDestroyed', 'XYKLiquidityMining.RewardClaimed');
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.multisig_call_activity_mv TO price_data.multisig_call_activity (`block_height` UInt32, `extrinsic_index` Nullable(UInt32), `call_address` String, `block_timestamp` DateTime, `call_name` LowCardinality(String), `args_json` String, `ingested_at` DateTime) AS SELECT block_height, extrinsic_index, call_address, block_timestamp, call_name, args_json, ingested_at FROM price_data.raw_calls WHERE call_name IN ('Multisig.as_multi', 'Multisig.approve_as_multi', 'Multisig.as_multi_threshold_1', 'Multisig.cancel_as_multi');
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.multisig_event_activity_mv TO price_data.multisig_event_activity (`block_height` UInt32, `event_index` UInt32, `extrinsic_index` Nullable(UInt32), `block_timestamp` DateTime, `event_name` LowCardinality(String), `multisig` String, `actor` String, `call_hash` String, `timepoint_height` UInt32, `timepoint_index` UInt32, `has_timepoint` UInt8, `result_ok` Nullable(UInt8), `result_error_json` Nullable(String), `ingested_at` DateTime) AS SELECT block_height, event_index, extrinsic_index, block_timestamp, event_name, JSONExtractString(args_json, 'multisig') AS multisig, multiIf(JSONHas(args_json, 'approving'), JSONExtractString(args_json, 'approving'), JSONExtractString(args_json, 'cancelling')) AS actor, JSONExtractString(args_json, 'callHash') AS call_hash, toUInt32(JSONExtractInt(args_json, 'timepoint', 'height')) AS timepoint_height, toUInt32(JSONExtractInt(args_json, 'timepoint', 'index')) AS timepoint_index, toUInt8(JSONHas(args_json, 'timepoint')) AS has_timepoint, if(event_name = 'Multisig.MultisigExecuted', toNullable(toUInt8(JSONExtractString(args_json, 'result', '__kind') = 'Ok')), NULL) AS result_ok, if(event_name = 'Multisig.MultisigExecuted' AND JSONExtractString(args_json, 'result', '__kind') = 'Err', toNullable(JSONExtractRaw(args_json, 'result', 'value')), NULL) AS result_error_json, ingested_at FROM price_data.raw_events WHERE event_name IN ('Multisig.NewMultisig', 'Multisig.MultisigApproval', 'Multisig.MultisigExecuted', 'Multisig.MultisigCancelled');
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.nft_owner_latest_mv TO price_data.nft_owner_latest (`collection` String, `item` String, `owner` AggregateFunction(argMax, String, UInt64)) AS SELECT JSONExtractString(args_json, 'collection') AS collection, JSONExtractString(args_json, 'item') AS item, argMaxState(multiIf(event_name = 'Uniques.Burned', '', event_name = 'Uniques.Transferred', lower(JSONExtractString(args_json, 'to')), lower(JSONExtractString(args_json, 'owner'))), (toUInt64(block_height) * 4294967296) + event_index) AS owner FROM price_data.raw_events WHERE event_name IN ('Uniques.Issued', 'Uniques.Transferred', 'Uniques.Burned') GROUP BY collection, item;
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.ohlc_15min_mv TO price_data.ohlc_15min (`asset_id` UInt32, `interval_start` DateTime, `open_state` AggregateFunction(argMin, Decimal(38, 12), DateTime), `high_state` AggregateFunction(max, Decimal(38, 12)), `low_state` AggregateFunction(min, Decimal(38, 12)), `close_state` AggregateFunction(argMax, Decimal(38, 12), DateTime), `volume_buy_state` AggregateFunction(sum, Decimal(38, 12)), `volume_sell_state` AggregateFunction(sum, Decimal(38, 12))) AS SELECT asset_id, toStartOfInterval(block_timestamp, toIntervalMinute(15)) AS interval_start, argMinState(usd_price, block_timestamp) AS open_state, maxState(usd_price) AS high_state, minState(usd_price) AS low_state, argMaxState(usd_price, block_timestamp) AS close_state, sumState(usd_volume_buy) AS volume_buy_state, sumState(usd_volume_sell) AS volume_sell_state FROM price_data.prices WHERE block_timestamp > toDateTime(0) GROUP BY asset_id, interval_start;
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.ohlc_1d_mv TO price_data.ohlc_1d (`asset_id` UInt32, `interval_start` DateTime, `open_state` AggregateFunction(argMin, Decimal(38, 12), DateTime), `high_state` AggregateFunction(max, Decimal(38, 12)), `low_state` AggregateFunction(min, Decimal(38, 12)), `close_state` AggregateFunction(argMax, Decimal(38, 12), DateTime), `volume_buy_state` AggregateFunction(sum, Decimal(38, 12)), `volume_sell_state` AggregateFunction(sum, Decimal(38, 12))) AS SELECT asset_id, toStartOfDay(block_timestamp) AS interval_start, argMinState(usd_price, block_timestamp) AS open_state, maxState(usd_price) AS high_state, minState(usd_price) AS low_state, argMaxState(usd_price, block_timestamp) AS close_state, sumState(usd_volume_buy) AS volume_buy_state, sumState(usd_volume_sell) AS volume_sell_state FROM price_data.prices WHERE block_timestamp > toDateTime(0) GROUP BY asset_id, interval_start;
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.ohlc_1h_mv TO price_data.ohlc_1h (`asset_id` UInt32, `interval_start` DateTime, `open_state` AggregateFunction(argMin, Decimal(38, 12), DateTime), `high_state` AggregateFunction(max, Decimal(38, 12)), `low_state` AggregateFunction(min, Decimal(38, 12)), `close_state` AggregateFunction(argMax, Decimal(38, 12), DateTime), `volume_buy_state` AggregateFunction(sum, Decimal(38, 12)), `volume_sell_state` AggregateFunction(sum, Decimal(38, 12))) AS SELECT asset_id, toStartOfHour(block_timestamp) AS interval_start, argMinState(usd_price, block_timestamp) AS open_state, maxState(usd_price) AS high_state, minState(usd_price) AS low_state, argMaxState(usd_price, block_timestamp) AS close_state, sumState(usd_volume_buy) AS volume_buy_state, sumState(usd_volume_sell) AS volume_sell_state FROM price_data.prices WHERE block_timestamp > toDateTime(0) GROUP BY asset_id, interval_start;
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.ohlc_1m_mv TO price_data.ohlc_1m (`asset_id` UInt32, `interval_start` Date, `open_state` AggregateFunction(argMin, Decimal(38, 12), DateTime), `high_state` AggregateFunction(max, Decimal(38, 12)), `low_state` AggregateFunction(min, Decimal(38, 12)), `close_state` AggregateFunction(argMax, Decimal(38, 12), DateTime), `volume_buy_state` AggregateFunction(sum, Decimal(38, 12)), `volume_sell_state` AggregateFunction(sum, Decimal(38, 12))) AS SELECT asset_id, toStartOfMonth(block_timestamp) AS interval_start, argMinState(usd_price, block_timestamp) AS open_state, maxState(usd_price) AS high_state, minState(usd_price) AS low_state, argMaxState(usd_price, block_timestamp) AS close_state, sumState(usd_volume_buy) AS volume_buy_state, sumState(usd_volume_sell) AS volume_sell_state FROM price_data.prices WHERE block_timestamp > toDateTime(0) GROUP BY asset_id, interval_start;
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.ohlc_1w_mv TO price_data.ohlc_1w (`asset_id` UInt32, `interval_start` Date, `open_state` AggregateFunction(argMin, Decimal(38, 12), DateTime), `high_state` AggregateFunction(max, Decimal(38, 12)), `low_state` AggregateFunction(min, Decimal(38, 12)), `close_state` AggregateFunction(argMax, Decimal(38, 12), DateTime), `volume_buy_state` AggregateFunction(sum, Decimal(38, 12)), `volume_sell_state` AggregateFunction(sum, Decimal(38, 12))) AS SELECT asset_id, toStartOfWeek(block_timestamp, 1) AS interval_start, argMinState(usd_price, block_timestamp) AS open_state, maxState(usd_price) AS high_state, minState(usd_price) AS low_state, argMaxState(usd_price, block_timestamp) AS close_state, sumState(usd_volume_buy) AS volume_buy_state, sumState(usd_volume_sell) AS volume_sell_state FROM price_data.prices WHERE block_timestamp > toDateTime(0) GROUP BY asset_id, interval_start;
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.ohlc_30min_mv TO price_data.ohlc_30min (`asset_id` UInt32, `interval_start` DateTime, `open_state` AggregateFunction(argMin, Decimal(38, 12), DateTime), `high_state` AggregateFunction(max, Decimal(38, 12)), `low_state` AggregateFunction(min, Decimal(38, 12)), `close_state` AggregateFunction(argMax, Decimal(38, 12), DateTime), `volume_buy_state` AggregateFunction(sum, Decimal(38, 12)), `volume_sell_state` AggregateFunction(sum, Decimal(38, 12))) AS SELECT asset_id, toStartOfInterval(block_timestamp, toIntervalMinute(30)) AS interval_start, argMinState(usd_price, block_timestamp) AS open_state, maxState(usd_price) AS high_state, minState(usd_price) AS low_state, argMaxState(usd_price, block_timestamp) AS close_state, sumState(usd_volume_buy) AS volume_buy_state, sumState(usd_volume_sell) AS volume_sell_state FROM price_data.prices WHERE block_timestamp > toDateTime(0) GROUP BY asset_id, interval_start;
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.ohlc_4h_mv TO price_data.ohlc_4h (`asset_id` UInt32, `interval_start` DateTime, `open_state` AggregateFunction(argMin, Decimal(38, 12), DateTime), `high_state` AggregateFunction(max, Decimal(38, 12)), `low_state` AggregateFunction(min, Decimal(38, 12)), `close_state` AggregateFunction(argMax, Decimal(38, 12), DateTime), `volume_buy_state` AggregateFunction(sum, Decimal(38, 12)), `volume_sell_state` AggregateFunction(sum, Decimal(38, 12))) AS SELECT asset_id, toStartOfInterval(block_timestamp, toIntervalHour(4)) AS interval_start, argMinState(usd_price, block_timestamp) AS open_state, maxState(usd_price) AS high_state, minState(usd_price) AS low_state, argMaxState(usd_price, block_timestamp) AS close_state, sumState(usd_volume_buy) AS volume_buy_state, sumState(usd_volume_sell) AS volume_sell_state FROM price_data.prices WHERE block_timestamp > toDateTime(0) GROUP BY asset_id, interval_start;
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.ohlc_5min_mv TO price_data.ohlc_5min (`asset_id` UInt32, `interval_start` DateTime, `open_state` AggregateFunction(argMin, Decimal(38, 12), DateTime), `high_state` AggregateFunction(max, Decimal(38, 12)), `low_state` AggregateFunction(min, Decimal(38, 12)), `close_state` AggregateFunction(argMax, Decimal(38, 12), DateTime), `volume_buy_state` AggregateFunction(sum, Decimal(38, 12)), `volume_sell_state` AggregateFunction(sum, Decimal(38, 12))) AS SELECT asset_id, toStartOfFiveMinute(block_timestamp) AS interval_start, argMinState(usd_price, block_timestamp) AS open_state, maxState(usd_price) AS high_state, minState(usd_price) AS low_state, argMaxState(usd_price, block_timestamp) AS close_state, sumState(usd_volume_buy) AS volume_buy_state, sumState(usd_volume_sell) AS volume_sell_state FROM price_data.prices WHERE block_timestamp > toDateTime(0) GROUP BY asset_id, interval_start;
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.proxy_call_activity_mv TO price_data.proxy_call_activity (`real_account` String, `block_height` UInt32, `extrinsic_index` UInt32, `call_address` String, `block_timestamp` DateTime, `proxy_call_name` LowCardinality(String), `ingested_at` DateTime) AS SELECT lower(JSONExtractString(args_json, 'real')) AS real_account, block_height, assumeNotNull(extrinsic_index) AS extrinsic_index, call_address, block_timestamp, call_name AS proxy_call_name, ingested_at FROM price_data.raw_calls WHERE call_name IN ('Proxy.proxy', 'Proxy.proxy_announced') AND extrinsic_index IS NOT NULL AND match(lower(JSONExtractString(args_json, 'real')), '^0x[0-9a-f]{64}$');
-- Router operation id -> swapper, one row per Router entry on the event's operationStack.
-- Row-wise over the Broadcast event alone, so it needs no join and fills in any insertion
-- order. Pallet-broadcast arrived with spec 128 at block 12663601, so swaps below that
-- height emit no Broadcast event and cannot be covered here at all; the legacy era is
-- read through the pallet *Executed events instead (see swapEventFilterSql).
-- Broadcast names a swapper it does not have with a placeholder -- 0x2a2a..2a, or
-- the 'Parent' XCM origin marker -- most often for an XCM-originated swap with no
-- local origin. Those are dropped rather than stored: they encode 32 valid-looking
-- hex bytes, so a consumer would render one as a real SS58 account and assert an
-- actor that does not exist. Matched exactly, never by prefix: 0x2a2afcf3.. is an
-- ordinary account that merely starts the same way.
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.swap_actor_mv TO price_data.swap_actor (`block_height` UInt32, `operation_event_id` UInt64, `block_timestamp` DateTime, `swapper` String, `via_dca` UInt8, `ingested_at` DateTime) AS SELECT block_height, toUInt64(JSONExtractInt(arrayJoin(arrayFilter(x -> (JSONExtractString(x, '__kind') = 'Router'), JSONExtractArrayRaw(args_json, 'operationStack'))), 'value')) AS operation_event_id, block_timestamp, JSONExtractString(args_json, 'swapper') AS swapper, toUInt8(has(arrayMap(x -> JSONExtractString(x, '__kind'), JSONExtractArrayRaw(args_json, 'operationStack')), 'DCA')) AS via_dca, ingested_at FROM price_data.raw_events WHERE (event_name IN ('Broadcast.Swapped', 'Broadcast.Swapped2', 'Broadcast.Swapped3')) AND (JSONExtractString(args_json, 'swapper') NOT IN ('', '0x2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a', '0x506172656e740000000000000000000000000000000000000000000000000000'));

CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.swap_activity_mv TO price_data.swap_activity (`block_height` UInt32, `event_index` UInt32, `extrinsic_index` Nullable(UInt32), `block_timestamp` DateTime, `event_name` LowCardinality(String), `who` String, `asset_in` UInt32, `asset_out` UInt32, `amount_in` String, `amount_out` String, `ingested_at` DateTime) AS SELECT block_height, event_index, extrinsic_index, block_timestamp, event_name, JSONExtractString(args_json, 'who') AS who, toUInt32(greatest(0, JSONExtractInt(args_json, 'assetIn'))) AS asset_in, toUInt32(greatest(0, JSONExtractInt(args_json, 'assetOut'))) AS asset_out, multiIf(event_name IN ('XYK.SellExecuted', 'LBP.SellExecuted'), JSONExtractString(args_json, 'amount'), event_name IN ('XYK.BuyExecuted', 'LBP.BuyExecuted'), JSONExtractString(args_json, 'buyPrice'), JSONExtractString(args_json, 'amountIn')) AS amount_in, multiIf(event_name IN ('XYK.SellExecuted', 'LBP.SellExecuted'), JSONExtractString(args_json, 'salePrice'), event_name IN ('XYK.BuyExecuted', 'LBP.BuyExecuted'), JSONExtractString(args_json, 'amount'), JSONExtractString(args_json, 'amountOut')) AS amount_out, ingested_at FROM price_data.raw_events WHERE event_name IN ('Router.Executed', 'Router.RouteExecuted', 'XYK.SellExecuted', 'XYK.BuyExecuted', 'LBP.SellExecuted', 'LBP.BuyExecuted');
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.transfer_activity_by_time_mv TO price_data.transfer_activity_by_time (`block_height` UInt32, `event_index` UInt32, `extrinsic_index` Nullable(UInt32), `block_timestamp` DateTime, `event_name` LowCardinality(String), `from_account` String, `to_account` String, `amount` String, `asset_id` UInt32) AS SELECT block_height, event_index, extrinsic_index, block_timestamp, event_name, JSONExtractString(args_json, 'from') AS from_account, JSONExtractString(args_json, 'to') AS to_account, JSONExtractString(args_json, 'amount') AS amount, toUInt32(if(event_name = 'Balances.Transfer', 0, multiIf(JSONHas(args_json, 'currencyId'), JSONExtractInt(args_json, 'currencyId'), JSONHas(args_json, 'currency_id'), JSONExtractInt(args_json, 'currency_id'), JSONHas(args_json, 'assetId'), JSONExtractInt(args_json, 'assetId'), JSONHas(args_json, 'asset_id'), JSONExtractInt(args_json, 'asset_id'), 0))) AS asset_id FROM price_data.raw_events WHERE event_name IN ('Balances.Transfer', 'Tokens.Transfer', 'Currencies.Transferred');
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.transfer_activity_mv TO price_data.transfer_activity (`asset_id` UInt32, `block_height` UInt32, `event_index` UInt32, `extrinsic_index` Nullable(UInt32), `block_timestamp` DateTime, `event_name` LowCardinality(String), `from_account` String, `to_account` String, `amount` String) AS SELECT toUInt32(if(event_name = 'Balances.Transfer', 0, multiIf(JSONHas(args_json, 'currencyId'), JSONExtractInt(args_json, 'currencyId'), JSONHas(args_json, 'currency_id'), JSONExtractInt(args_json, 'currency_id'), JSONHas(args_json, 'assetId'), JSONExtractInt(args_json, 'assetId'), JSONHas(args_json, 'asset_id'), JSONExtractInt(args_json, 'asset_id'), 0))) AS asset_id, block_height, event_index, extrinsic_index, block_timestamp, event_name, if(JSONHas(args_json, 'from'), JSONExtractString(args_json, 'from'), JSONExtractString(args_json, 1)) AS from_account, if(JSONHas(args_json, 'to'), JSONExtractString(args_json, 'to'), JSONExtractString(args_json, 2)) AS to_account, if(JSONHas(args_json, 'amount'), JSONExtractString(args_json, 'amount'), JSONExtractString(args_json, 3)) AS amount FROM price_data.raw_events WHERE event_name IN ('Balances.Transfer', 'Tokens.Transfer', 'Currencies.Transferred');
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.vote_activity_mv TO price_data.vote_activity (`block_height` UInt32, `event_index` UInt32, `extrinsic_index` Nullable(UInt32), `call_address` Nullable(String), `block_timestamp` DateTime, `event_name` LowCardinality(String), `args_json` String, `ingested_at` DateTime) AS SELECT block_height, event_index, extrinsic_index, call_address, block_timestamp, event_name, args_json, ingested_at FROM price_data.raw_events WHERE event_name IN ('ConvictionVoting.Voted', 'Democracy.Voted');
-- Sibling of xcm_event_activity_mv on the same raw_events rows, not a chain off
-- its target: the two extraction expressions and the event-name filter below are
-- byte-identical to that view's, so the account-first table can only ever hold the
-- same rows the parent does (the same relationship transfer_activity_mv and
-- transfer_activity_by_time_mv have). It projects args_json away because the
-- account-scoped readers consume the extracted columns, not the payload.
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.xcm_event_activity_by_account_mv TO price_data.xcm_event_activity_by_account (`who` String, `block_height` UInt32, `event_index` UInt32, `extrinsic_index` Nullable(UInt32), `block_timestamp` DateTime, `event_name` LowCardinality(String), `asset_id` UInt32, `amount` String, `ingested_at` DateTime) AS SELECT JSONExtractString(args_json, 'who') AS who, block_height, event_index, extrinsic_index, block_timestamp, event_name, toUInt32(if((event_name IN ('Balances.Deposit', 'Balances.Issued', 'Balances.Endowed', 'Balances.Minted')), 0, multiIf(JSONHas(args_json, 'currencyId'), greatest(0, JSONExtractInt(args_json, 'currencyId')), JSONHas(args_json, 'currency_id'), greatest(0, JSONExtractInt(args_json, 'currency_id')), JSONHas(args_json, 'assetId'), greatest(0, JSONExtractInt(args_json, 'assetId')), JSONHas(args_json, 'asset_id'), greatest(0, JSONExtractInt(args_json, 'asset_id')), 0))) AS asset_id, JSONExtractString(args_json, 'amount') AS amount, ingested_at FROM price_data.raw_events WHERE event_name IN ('Currencies.Withdrawn', 'Currencies.Deposited', 'Tokens.Deposited', 'Balances.Deposit', 'Balances.Issued', 'Balances.Endowed', 'Tokens.Endowed', 'Balances.Minted', 'System.NewAccount', 'MessageQueue.Processed', 'DmpQueue.ExecutedDownward', 'XcmpQueue.Success', 'XcmpQueue.Fail', 'XTokens.TransferredAssets', 'XTokens.TransferredMultiAssets', 'PolkadotXcm.Sent');
-- The barrier and send names cover both runtime eras: MessageQueue.Processed /
-- XTokens.TransferredAssets since the block-5,433,625 MessageQueue migration, and
-- DmpQueue.ExecutedDownward + XcmpQueue.Success/Fail / XTokens.TransferredMultiAssets
-- before it -- the decoders pair legs with whichever barrier the era emitted.
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.xcm_event_activity_mv TO price_data.xcm_event_activity (`block_height` UInt32, `event_index` UInt32, `extrinsic_index` Nullable(UInt32), `block_timestamp` DateTime, `event_name` LowCardinality(String), `asset_id` UInt32, `who` String, `amount` String, `args_json` String, `ingested_at` DateTime) AS SELECT block_height, event_index, extrinsic_index, block_timestamp, event_name, toUInt32(if((event_name IN ('Balances.Deposit', 'Balances.Issued', 'Balances.Endowed', 'Balances.Minted')), 0, multiIf(JSONHas(args_json, 'currencyId'), greatest(0, JSONExtractInt(args_json, 'currencyId')), JSONHas(args_json, 'currency_id'), greatest(0, JSONExtractInt(args_json, 'currency_id')), JSONHas(args_json, 'assetId'), greatest(0, JSONExtractInt(args_json, 'assetId')), JSONHas(args_json, 'asset_id'), greatest(0, JSONExtractInt(args_json, 'asset_id')), 0))) AS asset_id, JSONExtractString(args_json, 'who') AS who, JSONExtractString(args_json, 'amount') AS amount, args_json, ingested_at FROM price_data.raw_events WHERE event_name IN ('Currencies.Withdrawn', 'Currencies.Deposited', 'Tokens.Deposited', 'Balances.Deposit', 'Balances.Issued', 'Balances.Endowed', 'Tokens.Endowed', 'Balances.Minted', 'System.NewAccount', 'MessageQueue.Processed', 'DmpQueue.ExecutedDownward', 'XcmpQueue.Success', 'XcmpQueue.Fail', 'XTokens.TransferredAssets', 'XTokens.TransferredMultiAssets', 'PolkadotXcm.Sent');
-- Fed from raw_events exactly as xcm_event_activity_mv is, not chained off its
-- target: the who / asset_id / amount expressions below are byte-identical to that
-- view's, so the two tables can never decide the same event differently. The filter
-- is the narrower one this projection exists for -- the walk's eight families, a
-- subset of the parent's twelve, in hook context.
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.xcm_inbound_walk_events_mv TO price_data.xcm_inbound_walk_events (`block_height` UInt32, `event_index` UInt32, `block_timestamp` DateTime, `event_name` LowCardinality(String), `who` String, `asset_id` UInt32, `amount` String, `ingested_at` DateTime) AS SELECT block_height, event_index, block_timestamp, event_name, JSONExtractString(args_json, 'who') AS who, toUInt32(if((event_name IN ('Balances.Deposit', 'Balances.Issued', 'Balances.Endowed', 'Balances.Minted')), 0, multiIf(JSONHas(args_json, 'currencyId'), greatest(0, JSONExtractInt(args_json, 'currencyId')), JSONHas(args_json, 'currency_id'), greatest(0, JSONExtractInt(args_json, 'currency_id')), JSONHas(args_json, 'assetId'), greatest(0, JSONExtractInt(args_json, 'assetId')), JSONHas(args_json, 'asset_id'), greatest(0, JSONExtractInt(args_json, 'asset_id')), 0))) AS asset_id, JSONExtractString(args_json, 'amount') AS amount, ingested_at FROM price_data.raw_events WHERE event_name IN ('Currencies.Deposited', 'Tokens.Deposited', 'Balances.Deposit', 'Balances.Issued', 'Balances.Endowed', 'Tokens.Endowed', 'Balances.Minted', 'System.NewAccount') AND extrinsic_index IS NULL;
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.xyk_pool_registry_mv TO price_data.xyk_pool_registry (`lp_asset_id` Int32, `pool_account` String, `asset_a` Int32, `asset_b` Int32, `created_block` UInt32, `ingested_at` DateTime) AS SELECT toInt32(JSONExtractInt(args_json, 'shareToken')) AS lp_asset_id, JSONExtractString(args_json, 'pool') AS pool_account, toInt32(JSONExtractInt(args_json, 'assetA')) AS asset_a, toInt32(JSONExtractInt(args_json, 'assetB')) AS asset_b, block_height AS created_block, ingested_at FROM price_data.raw_events WHERE event_name = 'XYK.PoolCreated';
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.xyk_pool_reserve_history_mv TO price_data.xyk_pool_reserve_history (`pool_account` String, `block_height` UInt32, `block_timestamp` DateTime, `asset_a` Int32, `asset_b` Int32, `reserve_a_raw` String, `reserve_b_raw` String, `ingested_at` DateTime) AS SELECT JSONExtractString(p, 'pool_account') AS pool_account, block_height, block_timestamp, toInt32(JSONExtractInt(p, 'asset_a')) AS asset_a, toInt32(JSONExtractInt(p, 'asset_b')) AS asset_b, JSONExtractString(p, 'reserve_a') AS reserve_a_raw, JSONExtractString(p, 'reserve_b') AS reserve_b_raw, ingested_at FROM price_data.raw_block_snapshots ARRAY JOIN JSONExtractArrayRaw(JSONExtractRaw(payload_json, 'xyk'), 'pools') AS p WHERE (block_height % 600) = 0;
-- The LP reconstruction's filter: Uniques.* restricted to the XYK farm deposit
-- collection, plus every XYK liquidity-mining lifecycle event. The collection is
-- Basilisk's `xykLiquidityMining.nftCollectionId` runtime constant (1); the job
-- re-applies the same scope itself from XYK_FARM_NFT_COLLECTION_ID in
-- api/src/derivations/jobs.ts, and jobs.test.ts holds the two literals together.
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.lp_lifecycle_events_mv TO price_data.lp_lifecycle_events (`block_height` UInt32, `event_index` UInt32, `extrinsic_index` Nullable(UInt32), `block_timestamp` DateTime, `event_name` LowCardinality(String), `collection` String, `item` String, `position_id` String, `deposit_id` String, `owner` String, `from_account` String, `to_account` String, `lp_token` Int32, `amount` String, `ingested_at` DateTime) AS SELECT block_height, event_index, extrinsic_index, block_timestamp, event_name, JSONExtractString(args_json, 'collection') AS collection, JSONExtractString(args_json, 'item') AS item, JSONExtractString(args_json, 'positionId') AS position_id, JSONExtractString(args_json, 'depositId') AS deposit_id, lower(JSONExtractString(args_json, 'owner')) AS owner, lower(JSONExtractString(args_json, 'from')) AS from_account, lower(JSONExtractString(args_json, 'to')) AS to_account, toInt32(JSONExtractInt(args_json, 'lpToken')) AS lp_token, JSONExtractString(args_json, 'amount') AS amount, ingested_at FROM price_data.raw_events WHERE ((event_name IN ('Uniques.Issued', 'Uniques.Transferred', 'Uniques.Burned')) AND (JSONExtractString(args_json, 'collection') = '1')) OR (event_name IN ('XYKLiquidityMining.SharesDeposited', 'XYKLiquidityMining.SharesRedeposited', 'XYKLiquidityMining.DepositDestroyed'));
-- An MV predicate sees only the row being inserted, so it cannot name the XYK
-- pool set: those events arrive from a different pipeline and, under backward
-- backfill, later. Nor is the set identifiable by id range — Basilisk registers
-- PoolShare assets both below and above the registry's sequential-id offset
-- (5, 7, 8, 15 … and 1000018), so any floor would silently drop whole pools. So
-- the projection takes every substrate token observation and the reconstruction
-- filters it to the real pool set (see xykTotalSharesInsertSql), which the chain's
-- size makes affordable. Source column reference is qualified because the
-- projection's asset_id shadows it.
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.xyk_lp_share_observations_mv TO price_data.xyk_lp_share_observations (`asset_id` Int32, `account_id` String, `block_height` UInt32, `observation_id` String, `total` Nullable(String), `ingested_at` DateTime) AS SELECT toInt32OrZero(raw_balance_observations.asset_id) AS asset_id, account_id, block_height, observation_id, total, ingested_at FROM price_data.raw_balance_observations WHERE asset_kind = 'substrate';
-- Swap-row filter mirrors swapEventFilterSql() in api/src/services/accountTradeVolume.ts,
-- the single source of truth for the Broadcast/legacy era split, so the watermarks
-- cover exactly the rows the netting reads (asserted in api/src/derivations/jobs.test.ts).
-- `block_height * 12` is the synthetic block-space partition clock, not the chain's
-- block time; it must stay identical to account_trade_volume's PARTITION BY or the
-- watermarks key on partitions the derived table does not have. See the note above
-- account_trade_volume in 001_tables.sql before changing it at a block-time change.
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.swap_source_partition_watermarks_mv TO price_data.swap_source_partition_watermarks (`p` UInt32, `src_ingest` SimpleAggregateFunction(max, DateTime), `src_maxb` SimpleAggregateFunction(max, UInt32), `src_max_ts` SimpleAggregateFunction(max, DateTime)) AS SELECT toYYYYMM(toDateTime(block_height * 12)) AS p, max(ingested_at) AS src_ingest, max(block_height) AS src_maxb, max(block_timestamp) AS src_max_ts FROM price_data.raw_events WHERE ((event_name IN ('Broadcast.Swapped', 'Broadcast.Swapped2', 'Broadcast.Swapped3')) AND (block_height >= 12663601)) OR ((event_name IN ('XYK.SellExecuted', 'XYK.BuyExecuted', 'LBP.SellExecuted', 'LBP.BuyExecuted')) AND (block_height < 12663601)) GROUP BY p;
-- who / asset_id / amount are extracted here exactly as the count arm and the row-path
-- sibling matcher in api/src/services/explorerService.ts used to extract them for
-- themselves — lower() on the account id, toUInt32 on currencyId, the amount left as
-- its raw integer string — so the pair still matches on identical values.
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.dust_lost_events_mv TO price_data.dust_lost_events (`block_height` UInt32, `event_index` UInt32, `who` String, `asset_id` UInt32, `amount` String, `block_timestamp` DateTime, `ingested_at` DateTime) AS SELECT block_height, event_index, lower(JSONExtractString(args_json, 'who')) AS who, toUInt32(JSONExtractInt(args_json, 'currencyId')) AS asset_id, JSONExtractString(args_json, 'amount') AS amount, block_timestamp, ingested_at FROM price_data.raw_events WHERE event_name = 'Tokens.DustLost';
-- The pallet/index pair is derived exactly as the three readers derived it for themselves,
-- so the projection can never place an event under a different referendum than the raw
-- scan did: `Democracy.%` names its referendum in `refIndex` and everything else (the
-- `Referenda.%` prefix) in `index`, and both go through the same toUInt32(JSONExtractInt(…))
-- the directory already applied. The filter is likewise the readers' own, including the
-- JSONHas guard that keeps out the pallet's non-referendum events (Democracy.Delegated,
-- Democracy.PreimageNoted, and the one Democracy.Vetoed, which carries a proposal hash
-- rather than a refIndex) and the Democracy.Voted exclusion that keeps 53,327 vote events
-- out of a lifecycle table.
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.referendum_lifecycle_events_mv TO price_data.referendum_lifecycle_events (`pallet` LowCardinality(String), `ref_index` UInt32, `block_height` UInt32, `event_index` UInt32, `extrinsic_index` Nullable(UInt32), `block_timestamp` DateTime, `event_name` LowCardinality(String), `args_json` String, `ingested_at` DateTime) AS SELECT if(event_name LIKE 'Democracy.%', 'democracy', 'opengov') AS pallet, toUInt32(if(event_name LIKE 'Democracy.%', JSONExtractInt(args_json, 'refIndex'), JSONExtractInt(args_json, 'index'))) AS ref_index, block_height, event_index, extrinsic_index, block_timestamp, event_name, args_json, ingested_at FROM price_data.raw_events WHERE ((event_name LIKE 'Referenda.%') AND JSONHas(args_json, 'index')) OR ((event_name LIKE 'Democracy.%') AND (event_name != 'Democracy.Voted') AND JSONHas(args_json, 'refIndex'));
-- Named scheduler outcomes, keyed by the task name so a reader that can compute a name can
-- find its outcome (the OpenGov enactment; see scheduler_named_dispatches). Both terminal
-- named events are kept, because they are different answers to "did the approved call run":
-- Scheduler.Dispatched carries a result (Ok, or a Module error), while
-- Scheduler.CallUnavailable means the preimage was gone by enactment time and the call never
-- ran at all — OpenGov referendum 33 is confirmed and has exactly that. Scheduler.Scheduled
-- and Scheduler.Canceled are deliberately absent: they report {when, index} and never the
-- name, so they cannot be attributed to a task. The JSONHas guard keeps the 217,925 anonymous
-- agenda dispatches out; event_name IN (…) prunes on the set(200) skip index, which the
-- LIKE 'Scheduler.%' form above could not use.
CREATE MATERIALIZED VIEW IF NOT EXISTS price_data.scheduler_named_dispatches_mv TO price_data.scheduler_named_dispatches (`task_id` String, `block_height` UInt32, `event_index` UInt32, `extrinsic_index` Nullable(UInt32), `block_timestamp` DateTime, `event_name` LowCardinality(String), `args_json` String, `ingested_at` DateTime) AS SELECT JSONExtractString(args_json, 'id') AS task_id, block_height, event_index, extrinsic_index, block_timestamp, event_name, args_json, ingested_at FROM price_data.raw_events WHERE (event_name IN ('Scheduler.Dispatched', 'Scheduler.CallUnavailable')) AND JSONHas(args_json, 'id');
